name: Update ng-shared package
on:
  repository_dispatch:
    types: 
      - update_ng_shared_package_major_version
jobs:
  update_ng-shared_package_job:
    runs-on: ubuntu-latest
    steps:
      - name: Node $
        uses: actions/setup-node@v2
        with:
          node-version: v16.13.1
          registry-url: "https://npm.pkg.github.com"
          scope: "@amgfelgueiras"
      - name: Install Angular CLI
        run: npm i -g @angular/cli
      - uses: actions/checkout@v2
      - name: Update PKGs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat package.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm install
          npm install @amgfelgueiras/typescript-package-starter@latest
          git add .
          git commit -m "ng-shared updated to the latest version"
          git push
